### ISSUE TITLE
Missing fontawesome-webfont.woff2

### ISSUE THREAD

**Issue by lessless** [lfridael/ember-cli-font-awesome#20]
Hello! There is a 404 error in console: GET http://localhost:4200/fonts/fontawesome-webfont.woff2?v=4.3.0 

can you confirm that?

**Comment by lfridael** [comment]
Fixed in v0.0.9 release.

To update:

```bash
npm install --save-dev ember-cli-font-awesome
```

**Comment by cravindra** [comment]
The issue seems to persist in v0.1.0

**Comment by lfridael** [comment]
@cravindra Without more info there's no way of telling why this error occurs for you.

If you clone this repo and use `ember serve` to run the test app, the Chrome inspector shows that the `woff2` font is being downloaded. http://127.0.0.1:4200/fonts/fontawesome-webfont.woff2?v=4.3.0

**Comment by cravindra** [comment]
Will try that and get back to you @lfridael
In case the problem persists, what information can I provide for diagnosis?
